# Generated by Django 4.1 on 2022-08-26 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Account_origin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_account_origin', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='thirdparty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_thirdparty', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
