# Generated by Django 4.1 on 2022-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_card_account_transaction_account_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='customer_id',
            field=models.IntegerField(default=None),
        ),
    ]
