# Generated by Django 4.1 on 2022-08-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_receipts_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='account_number',
            field=models.IntegerField(default=None),
        ),
    ]
