# Generated by Django 4.1 on 2022-08-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_receipts_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='receipt_type',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Receipts_transaction', to='wallet.account'),
        ),
    ]
