# Generated by Django 4.1 on 2022-08-26 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_receipts_receipt_type_alter_receipts_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
