# Generated by Django 4.1 on 2022-08-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_notifications_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
