# Generated by Django 4.1 on 2022-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='id_number',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
