# Generated by Django 4.1 on 2022-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_card_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(default=None),
        ),
    ]
