# Generated by Django 4.1 on 2022-08-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_card_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=None),
        ),
    ]
