# Generated by Django 4.1 on 2022-08-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_card_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.account'),
        ),
    ]
