# Generated by Django 4.1 on 2022-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_card_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_charge',
            field=models.IntegerField(default=None),
        ),
    ]
