# Generated by Django 4.1 on 2022-08-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
