# Generated by Django 4.1 on 2022-08-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_transaction_transaction_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=None),
        ),
    ]
