# Generated by Django 4.1 on 2022-08-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_wallet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='profile_pictures/'),
        ),
    ]
