# Generated by Django 4.1 on 2022-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
