# Generated by Django 4.1 on 2022-08-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_card_card_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdparty',
            old_name='name',
            new_name='full_name',
        ),
    ]
