# Generated by Django 4.1 on 2022-08-26 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0028_rename_name_thirdparty_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ThirdPary_currency', to='wallet.wallet'),
        ),
    ]
