# Generated by Django 4.1 on 2022-08-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0029_thirdparty_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='recepient',
        ),
        migrations.AddField(
            model_name='notifications',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Notifications_recipient', to='wallet.account'),
        ),
    ]
