# Generated by Django 4.1 on 2022-08-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0030_remove_notifications_recepient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reciepts_transaction', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
